# Railway Deployment Configuration

# Use Node.js 20
[build]
  builder = "nixpacks"
  buildCommand = "npm install && npm run build"
  
[deploy]
  command = "npm start"

# Health check endpoint
[health]
  path = "/"
  interval = 30
